trigger:
- master

# schedules:
# - cron: "0 4 * * *"
#   displayName: Nightly build at 0400 UTC
#   branches:
#     include:
#     - master
#   always: true

stages:
- stage: build_bba
  displayName: Build ECP5 chipdb (*.bba)
  jobs:
  - job: build_bba
    displayName: Build ECP5 chipdb (*.bba)
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - bash: ./build-bba.sh
      displayName: Build ECP5 chipdb (*.bba)
      name: build_bba
    - publish: _packages/build_linux_x86_64/ecp5-bba-linux_x86_64-nightly.tar.gz
      artifact: ecp5-bba
- stage: build_toolchain
  displayName: build toolchain
  jobs:
  - job: build_toolchain
    displayName: Build toolchain
    strategy:
      matrix:
        linux_x86_64:
          ARCH: linux_x86_64
          vm_image: ubuntu-18.04
        osx:
          ARCH: darwin
          vm_image: macOS-10.14
        # win64:
        #   ARCH: windows_amd64
        #   vm_image: vs2017-win2016
    pool:
      vmImage: '$(vm_image)'
    steps:
    - download: current
      artifact: ecp5-bba
    - bash: cp $(Pipeline.Workspace)/ecp5-bba/ecp5-bba-linux_x86_64-nightly.tar.gz $(Build.Repository.LocalPath)/chipdb.tar.gz
      displayName: Copy BBA artifact
    - bash: ./build.sh $(ARCH)
      displayName: Build toolchain
      name: build_toolchain  # identifier for this step (A-Z, a-z, 0-9, and underscore)
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: open-tool-forge-release
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'manual'
        tag: $(ARCH)-nightly-$(Date:yyyyMMdd)
        assets: |
          _packages/**/*.tar.gz
          _packages/**/*.zip
