trigger:
- master
stages:
- stage: build_bba
  displayName: build bba
  jobs:
  - job: build_bba
    displayName: Build ECP5 chipdbs (*.bba)
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - bash: ./build-bba.sh  # contents of the script to run
      displayName: Build ECP5 Chip DBs
      name: build_bba  # identifier for this step (A-Z, a-z, 0-9, and underscore)
    - publish: _packages/build_linux_x86_64/ecp5-bba-linux_x86_64-nightly.tar.gz
      artifact: ecp5-bba
