name: base
channels:
  - defaults
  - conda-forge
  - litex-hub # for libftdi
dependencies:
  - python=3.7
  - conda-forge::boost=1.72 # includes py-boost, has more recent releases
  - eigen
  - bison
  - flex
  - gawk
  - gettext
  - libftdi
  - libiconv
  - libusb
  - m4
  - make
  - ncurses
  - readline
