name: base
channels:
  - defaults
  - conda-forge
  - litex-hub # for libftdi
dependencies:
  - python=3.7
  - bison=3.4
  - eigen=3.3.7
  - flex=2.6.4
  - gawk=5.0.1
  - gettext=0.19.8.1
  - boost=1.72.0
  - libftdi=1.3
  - libiconv=1.15
  - libusb=1.0.23
  - m4=1.4.18
  - make=4.2
  - ncurses=6.1
  - py-boost=1.67
  - readline=8.0